pipeline:
  build:
    image: node:8.11
    commands:
      - npm install
      - npm run build
  docker:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: rsschool/ui
    tags: latest
  deploy:
    image: appleboy/drone-ssh
    host: 172.31.2.208
    secrets: [ ssh_key, ssh_username ]
    port: 22
    command_timeout: 60
    script:
      - sleep 20
      - docker pull rsschool/ui
      - docker-compose stop ui
      - docker-compose rm -f ui
      - docker-compose up -d ui
